server:
  port: 8073

spring:
  application:
    name: api
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.128:8848
        namespace: public
        group: Secondhand_GROUP
      config:
        server-addr: 192.168.150.128:8848
        namespace: public
        group: Secondhand_GROUP
        import-check:
          enabled: false
  autoconfigure:
    exclude:
      # 数据库相关排除
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      # rabbitmq排除
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

# OpenFeign 配置
feign:
  client:
    config:
      user-service:
        connectTimeout: 5000
        readTimeout: 5000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# 用户服务地址
user:
  service:
    url: http://localhost:8072
