server:
  port: 8081

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
      driver-class-name: ${tri.common.datasource.driver-class-name}
      url: jdbc:mysql://${tri.common.datasource.host}:${tri.common.datasource.port}/${tri.common.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${tri.common.datasource.username}
      password: ${tri.common.datasource.password}

  rabbitmq:
    host: 192.168.150.128
    port: 5672
    username: Secondhand
    password: 626520QQ
    virtual-host: /Secondhand

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tri.common.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
