server:
  port: 8071

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    nacos:
      server-addr: 192.168.150.128:8848 # nacos地址
      discovery:
        namespace: public
        group: Secondhand_GROUP
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/addresses/**
  rabbitmq:
    host: 192.168.150.128
    port: 5672
    username: Secondhand
    password: 626520QQ
    virtual-host: /Secondhand
  # 禁用数据源自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
